"""Database creation and add operation table

Revision ID: 67e965e474e2
Revises: 
Create Date: 2024-09-16 23:51:30.182168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e965e474e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.String(), nullable=False),
    sa.Column('gross_income', sa.Integer(), nullable=True),
    sa.Column('comission', sa.Integer(), nullable=True),
    sa.Column('revenue_after_comission', sa.Integer(), nullable=True),
    sa.Column('total_expense', sa.Integer(), nullable=True),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('date_of_payment', sa.Date(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
